version: '3'
services:
  app:
    build: .
    depends_on: 
      - redis
    environment:
      - DEMO_APP_ADDR=0.0.0.0:8080
      - DEMO_REDIS_ADDR=redis:6379

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #- ./mayankzerodha.key:/etc/nginx/ssl/mayankzerodha.key
      #- ./zerodha.crt:/etc/nginx/ssl/zerodha.crt
    ports:
      - 80:80
      - 443:443

volumes:
  redis_data:
